---
# Setting it to "true" in all worlds will be forbidden.
enable-multiworld-support: false # Methods: (true, false)
# To add more worlds usage - and "world_folder_name"
worlds:
- "world"
# =========================================
# To add more items/blocks usage - add id of the item
prohibited-items:
- 1 # Stone Block
# =========================================
# Being in "true" only those who have the "antiframeedit.place.bypass" permission will be able to put things in the frames, on the other hand if it is in "false" everyone will be able to put things in the frames.
only-admin-usage: true # Methods: (true, false)
# =========================================
no.place.item.frame: "§cYou do not have permission to put an item in a frame."
no.remove.item.frame: "§cYou do not have permission to remove an item in a frame."
prohibited.item.usage: "§cThe item you are trying to put is locked from the frames."
# =========================================
# Author: JonyGamesYT9 
# Permissions: antiframeedit.remove.bypass, antiframeedit.place.bypass
# =========================================
...
